// Converted using ConvPNG
// This file contains all the graphics sources for easier inclusion in a project
#ifndef __tiles_gfx__
#define __tiles_gfx__
#include <stdint.h>

#define tiles_gfx_transparent_color_index 0

#define bird_width 16
#define bird_height 16
#define bird_size 258
extern uint8_t bird_data[258];
#define bird ((gfx_sprite_t*)bird_data)
#define bird_45_width 16
#define bird_45_height 16
#define bird_45_size 258
extern uint8_t bird_45_data[258];
#define bird_45 ((gfx_sprite_t*)bird_45_data)
#define bird_90_width 16
#define bird_90_height 16
#define bird_90_size 258
extern uint8_t bird_90_data[258];
#define bird_90 ((gfx_sprite_t*)bird_90_data)
#define sprite_scoreboard_width 202
#define sprite_scoreboard_height 98
#define sprite_scoreboard_size 19798
extern uint8_t sprite_scoreboard_data[19798];
#define sprite_scoreboard ((gfx_sprite_t*)sprite_scoreboard_data)
#define sprite_2nd_1_width 64
#define sprite_2nd_1_height 32
#define sprite_2nd_1_size 2050
extern uint8_t sprite_2nd_1_data[2050];
#define sprite_2nd_1 ((gfx_sprite_t*)sprite_2nd_1_data)
#define sprite_2nd_0_width 64
#define sprite_2nd_0_height 32
#define sprite_2nd_0_size 2050
extern uint8_t sprite_2nd_0_data[2050];
#define sprite_2nd_0 ((gfx_sprite_t*)sprite_2nd_0_data)
#define sprite_number_00_width 22
#define sprite_number_00_height 32
#define sprite_number_00_size 706
extern uint8_t sprite_number_00_data[706];
#define sprite_number_00 ((gfx_sprite_t*)sprite_number_00_data)
#define sprite_number_01_width 22
#define sprite_number_01_height 32
#define sprite_number_01_size 706
extern uint8_t sprite_number_01_data[706];
#define sprite_number_01 ((gfx_sprite_t*)sprite_number_01_data)
#define sprite_number_02_width 22
#define sprite_number_02_height 32
#define sprite_number_02_size 706
extern uint8_t sprite_number_02_data[706];
#define sprite_number_02 ((gfx_sprite_t*)sprite_number_02_data)
#define sprite_number_03_width 22
#define sprite_number_03_height 32
#define sprite_number_03_size 706
extern uint8_t sprite_number_03_data[706];
#define sprite_number_03 ((gfx_sprite_t*)sprite_number_03_data)
#define sprite_number_04_width 22
#define sprite_number_04_height 32
#define sprite_number_04_size 706
extern uint8_t sprite_number_04_data[706];
#define sprite_number_04 ((gfx_sprite_t*)sprite_number_04_data)
#define sprite_number_05_width 22
#define sprite_number_05_height 32
#define sprite_number_05_size 706
extern uint8_t sprite_number_05_data[706];
#define sprite_number_05 ((gfx_sprite_t*)sprite_number_05_data)
#define sprite_number_06_width 22
#define sprite_number_06_height 32
#define sprite_number_06_size 706
extern uint8_t sprite_number_06_data[706];
#define sprite_number_06 ((gfx_sprite_t*)sprite_number_06_data)
#define sprite_number_07_width 22
#define sprite_number_07_height 32
#define sprite_number_07_size 706
extern uint8_t sprite_number_07_data[706];
#define sprite_number_07 ((gfx_sprite_t*)sprite_number_07_data)
#define sprite_number_08_width 22
#define sprite_number_08_height 32
#define sprite_number_08_size 706
extern uint8_t sprite_number_08_data[706];
#define sprite_number_08 ((gfx_sprite_t*)sprite_number_08_data)
#define sprite_number_09_width 22
#define sprite_number_09_height 32
#define sprite_number_09_size 706
extern uint8_t sprite_number_09_data[706];
#define sprite_number_09 ((gfx_sprite_t*)sprite_number_09_data)
#define sprite_dither_width 26
#define sprite_dither_height 6
#define sprite_dither_size 158
extern uint8_t sprite_dither_data[158];
#define sprite_dither ((gfx_sprite_t*)sprite_dither_data)
#define arrow_width 6
#define arrow_height 10
#define arrow_size 62
extern uint8_t arrow_data[62];
#define arrow ((gfx_sprite_t*)arrow_data)
#define pause_width 80
#define pause_height 50
#define pause_size 4002
extern uint8_t pause_data[4002];
#define pause ((gfx_sprite_t*)pause_data)
extern uint8_t tileset_tile_0_data[];
#define tileset_tile_0 ((gfx_sprite_t*)tileset_tile_0_data)
extern uint8_t tileset_tile_1_data[];
#define tileset_tile_1 ((gfx_sprite_t*)tileset_tile_1_data)
extern uint8_t tileset_tile_2_data[];
#define tileset_tile_2 ((gfx_sprite_t*)tileset_tile_2_data)
extern uint8_t tileset_tile_3_data[];
#define tileset_tile_3 ((gfx_sprite_t*)tileset_tile_3_data)
extern uint8_t tileset_tile_4_data[];
#define tileset_tile_4 ((gfx_sprite_t*)tileset_tile_4_data)
extern uint8_t tileset_tile_5_data[];
#define tileset_tile_5 ((gfx_sprite_t*)tileset_tile_5_data)
extern uint8_t tileset_tile_6_data[];
#define tileset_tile_6 ((gfx_sprite_t*)tileset_tile_6_data)
extern uint8_t tileset_tile_7_data[];
#define tileset_tile_7 ((gfx_sprite_t*)tileset_tile_7_data)
extern uint8_t tileset_tile_8_data[];
#define tileset_tile_8 ((gfx_sprite_t*)tileset_tile_8_data)
extern uint8_t tileset_tile_9_data[];
#define tileset_tile_9 ((gfx_sprite_t*)tileset_tile_9_data)
extern uint8_t tileset_tile_10_data[];
#define tileset_tile_10 ((gfx_sprite_t*)tileset_tile_10_data)
extern uint8_t tileset_tile_11_data[];
#define tileset_tile_11 ((gfx_sprite_t*)tileset_tile_11_data)
extern uint8_t tileset_tile_12_data[];
#define tileset_tile_12 ((gfx_sprite_t*)tileset_tile_12_data)
extern uint8_t tileset_tile_13_data[];
#define tileset_tile_13 ((gfx_sprite_t*)tileset_tile_13_data)
extern uint8_t tileset_tile_14_data[];
#define tileset_tile_14 ((gfx_sprite_t*)tileset_tile_14_data)
extern uint8_t tileset_tile_15_data[];
#define tileset_tile_15 ((gfx_sprite_t*)tileset_tile_15_data)
extern uint8_t tileset_tile_16_data[];
#define tileset_tile_16 ((gfx_sprite_t*)tileset_tile_16_data)
extern uint8_t tileset_tile_17_data[];
#define tileset_tile_17 ((gfx_sprite_t*)tileset_tile_17_data)
extern uint8_t tileset_tile_18_data[];
#define tileset_tile_18 ((gfx_sprite_t*)tileset_tile_18_data)
extern uint8_t tileset_tile_19_data[];
#define tileset_tile_19 ((gfx_sprite_t*)tileset_tile_19_data)
extern uint8_t tileset_tile_20_data[];
#define tileset_tile_20 ((gfx_sprite_t*)tileset_tile_20_data)
extern uint8_t tileset_tile_21_data[];
#define tileset_tile_21 ((gfx_sprite_t*)tileset_tile_21_data)
extern uint8_t tileset_tile_22_data[];
#define tileset_tile_22 ((gfx_sprite_t*)tileset_tile_22_data)
extern uint8_t tileset_tile_23_data[];
#define tileset_tile_23 ((gfx_sprite_t*)tileset_tile_23_data)
extern uint8_t tileset_tile_24_data[];
#define tileset_tile_24 ((gfx_sprite_t*)tileset_tile_24_data)
extern uint8_t tileset_tile_25_data[];
#define tileset_tile_25 ((gfx_sprite_t*)tileset_tile_25_data)
extern uint8_t tileset_tile_26_data[];
#define tileset_tile_26 ((gfx_sprite_t*)tileset_tile_26_data)
extern uint8_t tileset_tile_27_data[];
#define tileset_tile_27 ((gfx_sprite_t*)tileset_tile_27_data)
extern uint8_t tileset_tile_28_data[];
#define tileset_tile_28 ((gfx_sprite_t*)tileset_tile_28_data)
extern uint8_t tileset_tile_29_data[];
#define tileset_tile_29 ((gfx_sprite_t*)tileset_tile_29_data)
extern uint8_t tileset_tile_30_data[];
#define tileset_tile_30 ((gfx_sprite_t*)tileset_tile_30_data)
extern uint8_t tileset_tile_31_data[];
#define tileset_tile_31 ((gfx_sprite_t*)tileset_tile_31_data)
extern uint8_t tileset_tile_32_data[];
#define tileset_tile_32 ((gfx_sprite_t*)tileset_tile_32_data)
extern uint8_t tileset_tile_33_data[];
#define tileset_tile_33 ((gfx_sprite_t*)tileset_tile_33_data)
extern uint8_t tileset_tile_34_data[];
#define tileset_tile_34 ((gfx_sprite_t*)tileset_tile_34_data)
extern uint8_t tileset_tile_35_data[];
#define tileset_tile_35 ((gfx_sprite_t*)tileset_tile_35_data)
extern uint8_t tileset_tile_36_data[];
#define tileset_tile_36 ((gfx_sprite_t*)tileset_tile_36_data)
extern uint8_t tileset_tile_37_data[];
#define tileset_tile_37 ((gfx_sprite_t*)tileset_tile_37_data)
extern uint8_t tileset_tile_38_data[];
#define tileset_tile_38 ((gfx_sprite_t*)tileset_tile_38_data)
extern uint8_t tileset_tile_39_data[];
#define tileset_tile_39 ((gfx_sprite_t*)tileset_tile_39_data)
extern uint8_t tileset_tile_40_data[];
#define tileset_tile_40 ((gfx_sprite_t*)tileset_tile_40_data)
extern uint8_t tileset_tile_41_data[];
#define tileset_tile_41 ((gfx_sprite_t*)tileset_tile_41_data)
extern uint8_t tileset_tile_42_data[];
#define tileset_tile_42 ((gfx_sprite_t*)tileset_tile_42_data)
extern uint8_t tileset_tile_43_data[];
#define tileset_tile_43 ((gfx_sprite_t*)tileset_tile_43_data)
#define tileset_tiles_num 44
extern uint8_t *tileset_tiles_data[44];
#define tileset_tiles ((gfx_sprite_t**)tileset_tiles_data)
#define sizeof_tiles_gfx_pal 364
extern uint16_t tiles_gfx_pal[182];

#endif
